

services:
  # --- 1. Your C++ Hermes Server ---
  hermes_server:
    build: .
    command: tail -f /dev/null
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - hermes_build_cache:/app/build
    depends_on:
      - minio
    privileged: true
    environment:
      - S3_HOST=minio
      - S3_PORT=9000

  # --- 2. Your MinIO S3 Server ---
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  hermes_build_cache:
  minio_data:
